### ISSUE TITLE
Missing documentation: import

### ISSUE THREAD

**Issue by huylift** [html-screen-capture-js/html-screen-capture-js#11]
How does someone import the module? And do you have TypeScript bindings?

**Comment by alessandrobelli** [comment]
Same here, I'm using
`    import htmlScreenCaptureJs from 'html-screen-capture-js' `
but I get 
`"TypeError: Cannot read property 'capture' of undefined"`

**Comment by urikalish** [comment]
Thanks, I'll look into it, maybe I'm not exporting it correctly..
For now, you can just include the source file, and use the global variable.
e.g. htmlScreenCaptureJs.capture(...)
* See demo page

**Comment by urikalish** [comment]
Currently, it's exported only as a global window object, so for now, you can include the source file (/dist/html-screen-capture.min.js), and use the variable e.g. htmlScreenCaptureJs.capture(...)
See demo page.

**Comment by huylift** [comment]
This worked for me in the end:

```
import { capture, OutputType } from 'html-screen-capture-js';
...
    const output = capture(OutputType.STRING, window.document, {});
```

And in a TypeScript modules.d.ts:
```
declare module 'html-screen-capture-js' {
  const capture: any;
  const OutputType: any;
}
```

**Comment by urikalish** [comment]
Thanks!
