### ISSUE TITLE
Capture Specific html tag

### ISSUE THREAD

**Issue by msammar** [html-screen-capture-js/html-screen-capture-js#13]
I am trying to capture specific div with an ID using html-screen-capture-js. 
is it possible/supported, if not do you have any plans to support this feature

**Comment by urikalish** [comment]
Hi, currently it's not specifically supported (it's a good idea for a future feature), BUT it's possible in 2 ways:

(1) Specify OutputType.OBJECT as the 1st function parameter, go over the new returned document object and remove all the redundant elements by yourself. Once done, extract the string via newDocument.outerHTML

(2) Specify all the non-relevant elements using the ignore options on the 3rd function parameter (tagsOfIgnoredDocBodyElements, classesOfIgnoredDocBodyElements, attrKeyValuePairsOfIgnoredElements)

**Comment by urikalish** [comment]
@msammar You can subscribe to issue #42
