### ISSUE TITLE
Is IE10 supported by this library?

### ISSUE THREAD

**Issue by madushag** [html-screen-capture-js/html-screen-capture-js#15]
When I use this library in IE10, most of the styles definitions don't appear in the generated HTML.

An example of the same web page generated in IE10 and IE11.
![image](https://user-images.githubusercontent.com/40742475/79672486-68218880-81a0-11ea-9c75-b35c6ab90e3e.png)

**Comment by urikalish** [comment]
I'm afraid IE10 is not supported.
