### ISSUE TITLE
Bootstrap styled checkboxes and radioboxes aren't rendered

### ISSUE THREAD

**Issue by alimovz** [html-screen-capture-js/html-screen-capture-js#17]
Hey Uri,

I'm trying to get html screen capture to properly capture a page that has a form with Boostrap-styled check and radio boxes on it. But the script does not see them for some reason. Here is the page I'm trying to capture: https://ibb.co/Hq5vzRQ
And here is what actually gets captured: https://ibb.co/dJLGZ9c

Notice how the check and radio boxes are completely invisible. This does not happen with regular unstyled check and radio boxes. I have only tried Boostrap-styled ones but think this might be a problem with other custom boxes.

Do you have any pointers as to where in the code I should look to fix this?

**Comment by urikalish** [comment]
Yo
I will look into it and get back to you (hopefully in a few minutes/hours).
Anyway...
https://github.com/html-screen-capture-js/html-screen-capture-js/commit/d8f4f3ed0967e3d1a141d520a5127eb4c60dcd72

Thanks,
Kalish

**Comment by urikalish** [comment]
do u c it on the new dom?

**Comment by alimovz** [comment]
> 
> Do you see it on the new DOM? BTW... [d8f4f3e](https://github.com/html-screen-capture-js/html-screen-capture-js/commit/d8f4f3ed0967e3d1a141d520a5127eb4c60dcd72)

Yessir. Here is the part of the new DOM:
https://jsfiddle.net/twvzakhf/

And here is what's on the original DOM:
```
<div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="customCheck" name="example1">
                            <label class="custom-control-label" for="customCheck">Check this custom checkbox</label>
                        </div>
```

So the input tag is there, but for some reason I cannot see it.

**Comment by urikalish** [comment]
Can you please try placing a position:relative style on the parent div?

**Comment by alimovz** [comment]
So I have updated the original html to look like this (just the checkbox part):
```
<div class="custom-control custom-checkbox" **style="position: relative;"**>
                            <input type="checkbox" class="custom-control-input" id="customCheck" name="example1">
                            <label class="custom-control-label" for="customCheck">Check this custom checkbox</label>
                        </div>
```
This does not appear to have any effect on the outcome. The rendered div now has **_style="position: relative;"** attribute attached to it.

**Comment by urikalish** [comment]
Can u post somewhere or email me the complete output html text?

**Comment by alimovz** [comment]
Here it is, Uri, the complete output: https://jsfiddle.net/g5m6tLx7/

**Comment by urikalish** [comment]
the checkbox has opacity:0

**Comment by urikalish** [comment]
I can make it visible if I
1) Make it non-transparent with opacity:1;
2) Change its index with z-index:0;
3) Position it better with top:7px;left:0;
Maybe this platform is using css-keyframes or javascript animation to make it placed and visible?

**Comment by alimovz** [comment]
I see what you're doing. You want to make the actual <input /> re-appear. What Boostrap is doing though is it hides the actual <input .../> and places a small div in its place that looks kind of like a checkbox.

The relating CSS you're asking about is, I believe, below:
```
.custom-control-input {
    position: absolute;
    z-index: -1;
    opacity: 0;
}
```

And indeed, if I change z-index to 0 and opacity to 1, the actual <input type="checkbox" ../> reappears on the screen. Then it's just a matter of positioning it right as you pointed out.

But do you think there is a way to capture the DOM precisely as it's rendered with those custom DIVs?

**Comment by urikalish** [comment]
I do hope so. Do these divs exist in the output?

**Comment by alimovz** [comment]
They do according the inspect tool in Chrome. Here is the exact page I'm using html-screen-capture.js on:
https://jsfiddle.net/yosd6puh/

**Comment by urikalish** [comment]
OK... looks like I don't clone pseudo elements. I'll try to add support for this by tomorrow.

**Comment by alimovz** [comment]
On a separate note, Uri, here is how I expanded your code to accommodate preservation of values to checkboxes, radio boxes and inputs of types: email, date, time, number, search, tel:

```
const dom_type = domElm.getAttribute('type');
            const tag_name = domElm.tagName.toLowerCase();
            const input_types = ['text', 'email', 'date', 'time', 'number', 'search', 'tel'];
			if (tag_name === 'input' && input_types.find(e => e === dom_type)) {
				newElm.setAttribute('value', domElm.value);
			} else if(tag_name === 'textarea') {
                newElm.innerText = domElm.value;
            } else if(tag_name === 'input' && (dom_type === 'checkbox' || dom_type === 'radio')) {
                if(domElm.checked) {
                    newElm.setAttribute('checked', true);
                }else{
                    newElm.removeAttribute("checked");
                }
            } else if (tag_name === 'select' && domElm.children) {
				newElm.setAttribute('value', domElm.value);
				for (var i = domElm.children.length - 1; i >= 0; i--) {
					if (domElm.children[i].getAttribute('value') === domElm.value) {
						newElm.children[i].setAttribute('selected', '');
					} else {
						newElm.children[i].removeAttribute('selected');
					}
				}
			}
```

**select** and **input type text**, as you know, had already been there prior to the change.

**Comment by urikalish** [comment]
This is cool! Would you like me to invite you to the organization/repository, so you'll be able to just commit directly to the master branch?

**Comment by alimovz** [comment]
Would be great sir. Thank you.

**Comment by urikalish** [comment]
Cool. Expect an invite.
p.s. Only if you feel comfortable about it... you can send me an email to uri.kalish (at gmail) with your real identity...

**Comment by urikalish** [comment]
Do u wanna push your code to master?
Also, reading the documentation on MDN, it seems like domElm.tagName always returns a value in UPPERCASE, while a call for domElm.getAttribute(attrname) always transform its argument to LOWERCASE. So maybe we can skip some transformations done for safety.

**Comment by alimovz** [comment]
I have proposed a file change via the github interface. Not really sure what happens after that. I don't yet know how to push code to master to be quite honest with you. I will read up on it before I answer your questions intelligently.

**Comment by urikalish** [comment]
You can fork the repo and create a pull request

**Comment by urikalish** [comment]
I've created 2 separate issues. One for all form input types, and the other for pseudo elements. Closing this issue.
