### ISSUE TITLE
Capture all form input types

### ISSUE THREAD

**Issue by urikalish** [html-screen-capture-js/html-screen-capture-js#18]

**Comment by alimovz** [comment]
Hey dude, so I have forked the code and made the necessary changes to address this issue. I can't figure out how to merge the code to yours. Can you provide some insight?

**Comment by urikalish** [comment]
You do that by creating a pull request. Just see that you don't switch the
source with the destination.

p.s. You can add me to WhatsApp for a quicker communication
+972547835888

בתאריך יום ו׳, 24 באפר׳ 2020, 02:06, מאת alimovz ‏<notifications@github.com

**Comment by urikalish** [comment]
Enhancement implemented by alimovz as part of v1.0.37
Closing this issue
