### ISSUE TITLE
Minimize number of unique classes

### ISSUE THREAD

**Issue by urikalish** [html-screen-capture-js/html-screen-capture-js#20]

**Comment by gal1419** [comment]
@urikalish  Can you please edit the description of this issue and elaborate?

**Comment by yamelkaya** [comment]
Hi! 
Thanks a lot for your library. It's really useful! But the problem of minimizing css classes is really important especially in the case of pseudo selectors. I tried to take a screenshot on Safari browser and it was nearly 25Mb. I checked which original classes generate so many new classes and found that majority of them were in invisible containers (with `display:none`). So, after replacing fully copypasted pseudo-selectors and ignoring invisible elements it was less than 2Mb. You can check out the large file here.   

[a9e158fc-01e6-4b5d-900e-395acb6b51eb.txt](https://github.com/html-screen-capture-js/html-screen-capture-js/files/4938765/a9e158fc-01e6-4b5d-900e-395acb6b51eb.txt)

I also would like to propose to add some options for ignoring invisible elements (`display: none` or `visibility: hidden`)

**Comment by gal1419** [comment]
@yamelkaya thanks for the feedback, ignoring hidden elements sounds reasonable. I’ll take a look

**Comment by urikalish** [comment]
@yamelkaya 
You can use the new **1.0.47** version I've just published.
I added support to ignore elements by their computed style via a new computedStyleKeyValuePairsOfIgnoredElements object inside the options parameter.
As you can see in the readme, its default value is {display: 'none'}, meaning hidden (via display:none) elements will not be cloned into the new HTML document.
I did **NOT** include visibility:'hidden' as part of its default value since it will cause a change in screenshot appearance vs. the original page, which is problematic if you're going for as accurate as possible capture, but if you insist you need it, you can simply override it in the options parameter as in this example:
const htmlDocStr = capture(
	OutputType.STRING,
	window.document,
	{
		**computedStyleKeyValuePairsOfIgnoredElements: {
			display: 'none',
			visibility: 'hidden'
		}**
	}
);

**Comment by yamelkaya** [comment]
@urikalish Thanks a lot for a new version and quick reply!
