### ISSUE TITLE
Cannot decode BASE64 generated string into image

### ISSUE THREAD

**Issue by alimovz** [html-screen-capture-js/html-screen-capture-js#3]
I have this code on a simple HTML page:

```
<script type="text/javascript" src="js/html-screen-capture.js"></script>
<script>
setTimeout(function(){
	let str = htmlScreenCaptureJs.capture(
		    htmlScreenCaptureJs.OutputType.BASE64,
		    window.document,
		    {
		        'imageFormatForDataUrl': 'image/jpeg',
		        'imageQualityForDataUrl': 1.0
		    }
		);
		console.log(str);
}, 5000);
</script>
```

I am then trying to decode the resulting base64 string into an image in PHP like so:
```
header('Content-Type: image/jpeg');
$data = file_get_contents("/tmp/screenshot.txt");
echo base64_decode($data);
```

But nothing gets rendered. Am I doing something wrong?

**Comment by msammar** [comment]
could you please clarify, how did you fix this issue?, I am facing same issue.

**Comment by urikalish** [comment]
What's coded into base64 is the new html document text, so if you decode it you'll get back html text. Note that the library does not save an actual image of the page. I think it's better to think about it as a single page standalone "html snapshot".

**Comment by alimovz** [comment]
> 
> 
> could you please clarify, how did you fix this issue?, I am facing same issue.

As Uri Kalish explained, the reason my code:
```
header('Content-Type: image/jpeg');
$data = file_get_contents("/tmp/screenshot.txt");
echo base64_decode($data);
```
did not render anything is because when the data gets base64 decoded, simple HTML is returned so header('Content-Type: image/jpeg'); won't show anything.
