### ISSUE TITLE
HTML screen capture is not taking textarea contents

### ISSUE THREAD

**Issue by maddan** [html-screen-capture-js/html-screen-capture-js#34]
html-screen-capture-js is not capturing the textarea contents. Is this a known issue? Please advise.

<textarea type="text"....></textarea>

**Comment by urikalish** [comment]
Hi maddan,
For me, text area controls are working as expected.
You can try the demo page ( https://dazzling-morse-a38f6a.netlify.app/) - it contains a textarea control.
Are you running the latest version?
What browser are you using?

**Comment by urikalish** [comment]
closed
