### ISSUE TITLE
how to create a screen capture "image" of an element

### ISSUE THREAD

**Issue by ctf0** [html-screen-capture-js/html-screen-capture-js#37]
i've read the docs but i cant find where i can export the result to a base64 image of what was captured 😢 

also is it possible to capture a specific element ex.`document.querySelector('[data-export]')` ?

**Comment by urikalish** [comment]
This library returns a new lightweight, self-contained HTML document in several formats, but NOT an image. More details on the readme page.

**Comment by ctf0** [comment]
from the docs
> This library can be used to:
> - Create a web page screen capture "image", and display the "snapshot" (e.g. by using an iframe).

**Comment by urikalish** [comment]
As you can see it's not really an image - that is why we added quotes...
Regarding capturing a single element - that's a good idea - I'll add it as a new issue.
Thanks!

**Comment by ctf0** [comment]
perfect, could u plz ping me when added ?

**Comment by urikalish** [comment]
@ctf0 Sure. You can also just subscribe to issue #42
