### ISSUE TITLE
The logLevel "off"  makes no sense

### ISSUE THREAD

**Issue by Tindtily** [html-screen-capture-js/html-screen-capture-js#38]
as subject

**Comment by urikalish** [comment]
It disables the lib from writing anything to the console - even errors. I'm not sure why people might want to use this settings, but since this lib can be consumed in all sorts of unknown situations, having this options seems ok to me. Do you disagree?

**Comment by Tindtily** [comment]
Thank you very much for your reply. I agree with you, I want to write nothing when the lib was used in production, but this setting doesn't work！

**Comment by urikalish** [comment]
Oops :) that is indeed something that needs fixing.

**Comment by urikalish** [comment]
Fixed in commit b5fab3486a8d77a89b3ddac19433cffb76a48894
Thanks!

**Comment by Tindtily** [comment]
So when the new version will be released?

**Comment by urikalish** [comment]
@Tindtily In about an hour

**Comment by urikalish** [comment]
@Tindtily 
1.0.48 is published.
Enjoy
