### ISSUE TITLE
How to preserve form field values when capturing a page?

### ISSUE THREAD

**Issue by alimovz** [html-screen-capture-js/html-screen-capture-js#4]
I'm working on a script that captures a page with a sign up form on it. I need to later be able to see what the visitor entered into the form. This is done for compliance.

html-screen-capture-js works great when capturing the page, but it captures the page in its original state, meaning if you enter something into a form on the page and then capture the screen, you won't see what was entered. Is there a way to also capture the form field values entered in real time?

**Comment by urikalish** [comment]
Sorry for the late response...
If we're talking about simple input tags, the current value can be added as a value attribute to the html node (or replace the default value which is already there), so it looks like an easy thing to support. Would that be ok?

**Comment by alimovz** [comment]
This is precisely what I did. Essentially I had to set the value attribute to what has just been entered:
```
$j(this).focusout(function(){
     $j(this).attr("value", $j(this).val());
});
```
or for a select:
```
$j(this).focusout(function(){
    $j(this).children().each(function(){
	$j(this).attr('selected', false);
     });
     $j(this).children('[value="'+$j(this).val()+'"]').attr('selected', true);
});
```

What characters would you escape though? I'm not escaping anything.

**Comment by urikalish** [comment]
cool, seems like the problematic chars (e.g. < > " ' &) are already taken care of by the attr function

**Comment by urikalish** [comment]
I've added support for 2 types of fields: input-text, and select-options.

**Comment by alimovz** [comment]
Hey Uri, do you see a problem if I extended the functionality of the feature you added for input-text to textarea?

```
if (domElm.tagName.toLowerCase() === 'input' && domElm.getAttribute('type') === 'text') {
	newElm.setAttribute('value', domElm.value);
} else if(domElm.tagName.toLowerCase() === 'textarea') {
        newElm.innerText = domElm.value;
} else if (domElm.tagName.toLowerCase() === 'select' && domElm.children) {...
...
```

**Comment by urikalish** [comment]
Hi,
Looks cool to me!

Thanks,
Uri Kalish

בתאריך יום ד׳, 15 באפר׳ 2020, 03:12, מאת alimovz ‏<notifications@github.com
