### ISSUE TITLE
The c0 class can't be customized

### ISSUE THREAD

**Issue by Tindtily** [html-screen-capture-js/html-screen-capture-js#46]
https://github.com/html-screen-capture-js/html-screen-capture-js/blob/f77e71849d2019c1f25b89cab3c334b4ba312389/src/capturer.ts#L61

I want to place two capture in one html, but with different style. But because the c0 class is conflict, I have to replace the entire string manully manually.

**Comment by urikalish** [comment]
@Tindtily 
You are correct, it should use the value of prefixForNewGeneratedClasses from the options object.
I'm on it.

**Comment by urikalish** [comment]
@Tindtily 
Done. You can upgrade to version 1.0.49 and set any value you want in prefixForNewGeneratedClasses in the options object.

**Comment by Tindtily** [comment]
https://github.com/html-screen-capture-js/html-screen-capture-js/blob/d5f9fa6d4352d69780b4e08542c7622803099b9b/src/capturer.ts#L278

by the way, there is one missing。

**Comment by urikalish** [comment]
@Tindtily 1.0.50
Thanks!
