### ISSUE TITLE
OutputType base64

### ISSUE THREAD

**Issue by anniehsp** [html-screen-capture-js/html-screen-capture-js#47]
Hi! I am trying to use html-screen-capture-js for my webpage. (Btw, thanks for the assume library), but I had trouble with OutputType.base64.

When I used this code, and try to put base64 image into my <img src> tag, it didn't show the image. So I was wondering if I used it wrong way. 

import { capture, OutputType } from 'html-screen-capture-js';
...
const str = capture(
    OutputType.BASE64,
    window.document,
    {
        rulesToAddToDocStyle: [
            '*,*::before,*::after{font-family:Arial,sans-serif !important;}',
        ],
        imageFormatForDataUrl: 'image/jpeg',
        imageQualityForDataUrl: 1.0
    }
);

this.setState({ imageUrl: str });
....

<img src={`data:image/jpeg;base64` +  this.state.imageUrl} />

So I tested with the different base64 encoding url to see if the code was wrong, but it was working fine and I really need help with this.

Thanks for spending time to read this and I will be waiting for your reply~

**Comment by urikalish** [comment]
@anniehsp Sorry for the late response...
If you don't need the ENTIRE output as base64, you can just send OutputType.STRING or OutputType.OBJECT as the first parameter to the capture function. All images are automatically encoded to base64 by the library, so you don't have to worry about that.
