### ISSUE TITLE
js script in body not saved even if tagsOfIgnoredDocBodyElements is []

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [html-screen-capture-js/html-screen-capture-js#49]
```html
...
<body>
...
<script src="data/1235.js?12365"></script>
</body>
```

output does not contain a script

**Comment by urikalish** [comment]
@T35R6braPwgDJKq  Sorry for the late response...
Scripts are external dependency and are not copied to the captured html, but you can work your way around this.
You can either (1) Store your js in a location that can be accessed from the client opening the captured HTML (e.g. http://public-location/js/1235.js) and inject a script with a src tag, or (2) Copy the entire js file and inject a script tag with the actual js text.

In either case, you will need to send OutputType.OBJECT as the first parameter to the capture method, get the result (it will return an HTML document), and add the script tag to the DOM via js code.
e.g.
//capture and get back result as an HTML document object
const htmlDoc = capture(OutputType.OBJECT);

//create a tag DOM element and append it
myScript = document.createElement('script');
myScript.setAttribute('src', 'http://public-location/js/1235.js');
htmlDoc.body.appendChild(myScript);

//convert the doc to str for further handling like storing it etc.
const htmlDocStr = htmlDoc.outerHTML;

Please update if that works for you.
