### ISSUE TITLE
Script dosn't capture Canvas elements.

### ISSUE THREAD

**Issue by karolmarchewka** [html-screen-capture-js/html-screen-capture-js#5]
Hello,

Your script works great for the HTML and SVG elements but capturing a Canvas element doesn't work as expected. The script can't capture what is inside a canvas and returns a canvas without its content.

**Comment by urikalish** [comment]
Thanks, you are correct, I haven't dealt with canvas elements yet.

**Comment by urikalish** [comment]
Canvas is now supported (v1.0.26)
