### ISSUE TITLE
I want to capture only certain class

### ISSUE THREAD

**Issue by maddan** [html-screen-capture-js/html-screen-capture-js#57]
Currently i'm not able to capture only certain parts of the html. Currently only window.document is working for us. :(

**Comment by maddan** [comment]
const capturedObj = capture(OutputType.BASE64, window.document,
      {
        classesOfIgnoredDocBodyElements: [
          // ..

We are using Base64 and if I use specific class that I wanna capture instead of window.document, i run into the error. 
"message":"Error while calling <servicename> The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null",

**Comment by urikalish** [comment]
Hi @maddan,
The 2nd argument to the capture method should always be the HTML document. If you want to ignore some elements in the page, you need to specify them as part of the the 3rd argument (options). See the for options readme ( https://github.com/html-screen-capture-js/html-screen-capture-js/blob/master/README.md )
