### ISSUE TITLE
Capture fixes widths and prevents responsiveness.

### ISSUE THREAD

**Issue by jcgentr** [html-screen-capture-js/html-screen-capture-js#60]
<img width="360" alt="Screen Shot 2021-09-30 at 11 05 07 AM" src="https://user-images.githubusercontent.com/20710009/135483085-624d2576-65dd-4fb1-8eb0-2e0e0cdbe43b.png">

It seems the width is being fixed on capture. This prevents having a responsive html webpage.

I would like to be able to keep widths 100% and keep the responsiveness of the webpage.

The easiest way to test this is to have the dev tools open when you capture. There will be whitespace in the captured html file where the dev tool was located. 

I am using create-react-app with tailwind.css.

**Comment by urikalish** [comment]
@jcgentr
Indeed, the widths (same as other properties) are saved exactly as they are in the original document to try and produce an exact image-like copy.
