### ISSUE TITLE
Operator instanceof SVGAnimatedString false negative

### ISSUE THREAD

**Issue by twjasa** [html-screen-capture-js/html-screen-capture-js#65]
Hello, 

I've been debugging my code trying to find where occurs an exception and find out the following:
![image](https://user-images.githubusercontent.com/12849040/146085900-91873cb7-556f-4d6a-a812-a8679ed7eeb8.png)

Notice that the object is a `SVGAnimatedString Prototype`  and still the operator results false. Also I tried to compare it using toString() and it results true. This is causing a javascript exception right in the `98` line where is trying to `split` an object instead of a string.

Not sure what is happening, this bug have been haunting my team for about a week.

If you don't mind I can create a PR to solve this issue by changing the operator, or maybe do you think that there is a better solution?

**Comment by urikalish** [comment]
@twjasa Thank you for reaching out, and sorry for this defect. If you could create a PR that would be great.

p.s. What is your product and use case for using this library?

**Comment by twjasa** [comment]
No problem @urikalish, I will create the PR shortly. 

It's used by a private product of ICE Mortgage Technology. There is a specific requirement where we have to send a replica of a React component with all styles to the backend in a HTML format.

**Comment by urikalish** [comment]
@twjasa Thank you. I'll merge your fix.

**Comment by urikalish** [comment]
Merged and published a new version 2.0.1 with your fix.
Thank you again.
