### ISSUE TITLE
Cannot bundle via webpack

### ISSUE THREAD

**Issue by plat2eau** [html-screen-capture-js/html-screen-capture-js#7]
I was packing the library into a javascript file via webpack and it doesn't load complete dependencies into the build file. I'm not sure if I'm going wrong somewhere or if this is really an issue. Please help

bundled js:

(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
let str = htmlScreenCaptureJs.capture(
    htmlScreenCaptureJs.OutputType.STRING,
    window.document,
    {
        'imageFormatForDataUrl': 'image/jpeg',
        'imageQualityForDataUrl': 1.0
    }
);
console.log(str);
},{}]},{},[1]);

**Comment by urikalish** [comment]
This looks like the example code from the readme file...???

**Comment by plat2eau** [comment]
Yes, it is. I am actually new to this and I couldn't bundle it so I used puppeteer instead to take screenshot.
