### ISSUE TITLE
Background of canvas black

### ISSUE THREAD

**Issue by Bariskau** [html-screen-capture-js/html-screen-capture-js#72]
First of all, thank you for this beautiful library.

I have a problem that when I render the html text created by the library, the background of the canvas looks problematic. I explained the situation in the image below.

![Screenshot from 2022-11-19 14-56-43](https://user-images.githubusercontent.com/48124441/202849682-9844187f-5094-4642-86b1-2a25daf08874.png)

**Comment by urikalish** [comment]
@Bariskau Is there a simple way to correct this issue in the output HTML e.g. adding a white background to the image container?

**Comment by Bariskau** [comment]
@urikalish Unfortunately, it's not a very sensible solution.  I am developing a screen shoot tool that works on the client side.  For this reason, I have no chance to intervene manually. It would make more sense to convert the canvas element to png instead. An option can be added for this.

**Comment by urikalish** [comment]
I understand, I'm just asking, assuming this output HTML, what would be the required fix for this issue?

**Comment by urikalish** [comment]
We can also discuss this on Discord if you like

**Comment by Bariskau** [comment]
Yes, we can discuss it over discord. We can also discuss the potential for **Video** and **Canvas** elements.

```javascript
let canvasToImg = () => {
    let canvas2ImgStr = ''
    const canvasList = document.getElementsByTagName('canvas');
    for (let i = 0; i < canvasList.length; i++) {
        const el = canvasList[i]
        let canvasDataUrl;
        // check visibility
        if (Boolean(el.offsetParent || el.offsetWidth || el.offsetHeight)) {
            try {
                canvasDataUrl = el.toDataURL('image/png', 1.0);
            } catch (e) {
                canvasDataUrl = '';
            }
        } else {
            canvasDataUrl = '';
        }
        canvas2ImgStr += `<img id="${i}" src="${canvasDataUrl}">`;
    }

    return canvas2ImgStr
}

let videoToImg = () => {
    let videoImgStr = ''
    let videoList = document.getElementsByTagName('video');
    for (let i = 0; i < videoList.length; i++) {
        const poster = videoList[i].getAttribute('poster');
        if (poster)  videoImgStr += `<img id="${i}" src="${poster}">`;
        else videoImgStr += ``;
    }
    return videoImgStr
}
```

**Comment by urikalish** [comment]
@Bariskau https://discord.gg/XE6HBcQ6

**Comment by urikalish** [comment]
@Bariskau I'm already transforming each canvas into a PNG with dataURL...

**Comment by Bariskau** [comment]
@urikalish I had a problem with the alpha channel because the **imageFormatForDataUrl** parameter is image/jpeg. I don't understand why it took me so long to realise this :) 

But adding the **poster** image for the **video tag** can be useful.
