### ISSUE TITLE
Cannot decode BASE64 generated string into image

### ISSUE THREAD

**Issue by peterlaw108** [html-screen-capture-js/html-screen-capture-js#8]
<script type="text/javascript" src="js/html-screen-capture.min.js"></script>
<script>
let str = htmlScreenCaptureJs.capture(
    htmlScreenCaptureJs.OutputType.BASE64,
    window.document,
    {
        'imageFormatForDataUrl': 'image/jpeg',
        'imageQualityForDataUrl': 1.0
    }
);
console.log(str);
</script>

PHP:
header('Content-Type: image/jpeg');
$data = file_get_contents("pic.jpg");
echo base64_decode($data);

**Comment by urikalish** [comment]
If you specify OutputType as BASE64, the **ENTIRE** new html document (as a string) will be coded as base64 - not just the image data.
The images inside your web page are coded to base64 data url in any case, no matter what you specify as the desired output type for the whole web page.
